### ISSUE TITLE
will you make a compatible version for Velocity?

### ISSUE THREAD

**Issue by XenWayne** [andylizi/haproxy-detector#2]
The way velocity handle HAproxy is same as the Bungeecord，direct/proxy can not work at same time either.

**Comment by andylizi** [comment]
I had a look at Velocity, and I'm willing to give it a try. Unfortunately I haven't used Velocity before and don't have a test environment set up. Will you be willing to test it for me? I've sent a friend request to your QQ listed in your website.

**Comment by andylizi** [comment]
Done in v3.0.0
