### ISSUE TITLE
Velocity冲突问题

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [andylizi/haproxy-detector#5]
在服务器中如果只启用spigot.yml的bungeecord = true将无法连接到服务器，提示无法连接至**If you wish to use IP forwarding, please enable it in your BungeeCord config as well!**
如果启用paper.yml中的proxy-protocol选项也将无法进入服务器，提示**ReadTimeOut**且**下游服务器没有任何实质性的响应**
我在想这属不属于一个反向代理的逻辑BUG？

**Comment by andylizi** [comment]
你需要开启的是 Velocity 的 `haproxy-protocol` 选项，而不是 `paper.yml` 中的 `proxy-protocol`。后者和 BC/Velocity 没有联系。

**Comment by xiaoyueyoqwq** [comment]
> 你需要开启的是 Velocity 的 `haproxy-protocol` 选项，而不是 `paper.yml` 中的 `proxy-protocol`。后者和 BC/Velocity 没有联系，与这个插件不兼容，请关闭它。

你好
  能够收到您的回复我倍感荣幸，也非常感谢你能在百忙之中抽出时间来帮我解决问题；问题主要是如果我不开启Paper.yml中的“proxy-protocol”而只开启Velocity中“haproxy-protocol”选项我将会被提示**If you wish to use IP forwarding, please enable it in your BungeeCord config as well!**且无法进入下游服务器，Velocity反馈的信息和下游服务端反馈的信息一致，且下游服务端有相应

**Comment by xiaoyueyoqwq** [comment]
已经解决，感谢帮助
**我是傻逼**
